import pandas as pd

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler


class LeadPreprocessor(BaseEstimator, TransformerMixin):
    """
    Production preprocessing pipeline for the Lead Scoring model.

    Responsibilities:
    - Drop ID column
    - Cap known numerical outliers
    - One-hot encode categorical features
    - MinMax scale numerical features
    """

    NUMERICAL_FEATURES = [
        "age",
        "time_spent_on_website",
        "page_views_per_visit",
    ]

    CATEGORICAL_FEATURES = [
        "current_occupation",
        "first_interaction",
        "profile_completed",
        "last_activity",
        "print_media_type1",
        "print_media_type2",
        "digital_media",
        "educational_channels",
        "referral",
    ]

    REQUIRED_FEATURES = NUMERICAL_FEATURES + CATEGORICAL_FEATURES

    def __init__(self):
        self.preprocessor = ColumnTransformer(
            transformers=[
                (
                    "numerical",
                    MinMaxScaler(),
                    self.NUMERICAL_FEATURES,
                ),
                (
                    "categorical",
                    OneHotEncoder(
                        handle_unknown="ignore",
                        sparse_output=False,
                    ),
                    self.CATEGORICAL_FEATURES,
                ),
            ],
            remainder="drop",
        )

    def _prepare_dataframe(self, X):
        """
        Apply transformations that happen before sklearn preprocessing.
        """

        X = X.copy()

        # ID is not a model feature.
        if "ID" in X.columns:
            X = X.drop(columns=["ID"])

        # Match the outlier treatment used in the original notebook.
        if "website_visits" in X.columns:
            X["website_visits"] = X["website_visits"].clip(upper=9)

        if "page_views_per_visit" in X.columns:
            X["page_views_per_visit"] = X[
                "page_views_per_visit"
            ].clip(upper=6.266)

        return X

    def _validate_features(self, X):
        """
        Make sure all expected raw features are present.
        """

        missing_features = [
            feature
            for feature in self.REQUIRED_FEATURES
            if feature not in X.columns
        ]

        if missing_features:
            raise ValueError(
                f"Missing required features: {missing_features}"
            )

    def fit(self, X, y=None):
        """
        Learn preprocessing parameters from training data.
        """

        X = self._prepare_dataframe(X)
        self._validate_features(X)

        self.preprocessor.fit(X)

        return self

    def transform(self, X):
        """
        Apply already-learned preprocessing to new data.
        """

        X = self._prepare_dataframe(X)
        self._validate_features(X)

        return self.preprocessor.transform(X)

    def fit_transform(self, X, y=None):
        """
        Fit preprocessing on data and transform it.
        """

        X = self._prepare_dataframe(X)
        self._validate_features(X)

        return self.preprocessor.fit_transform(X)

    def get_feature_names_out(self):
        """
        Return the final feature names generated by preprocessing.
        """

        return self.preprocessor.get_feature_names_out()